OPENAI_API_VERSION='2023-05-15'

AZURE_OPENAI_ENDPOINT='https://elsai-dev.openai.azure.com/'

AZURE_OPENAI_API_KEY='d2d05917a33d4c8e8ffb00ea56d47be3'

AZURE_MODEL_DEPLOYMENT_NAME='gpt-4o-mini'

VISION_KEY='e8b9dbb73bb24528ab6e7e671832c5cf'

VISION_ENDPOINT='https://aandm.cognitiveservices.azure.com/'

PEZZO_API_KEY='pez_eb3f4b55e8d537a6df41707ee858dd96'

PEZZO_PROJECT_ID='cm9mfktoa006eqk0hwujrv21k'

PEZZO_SERVER_URL='https://elsai-prompts-proxy.optisolbusiness.com'

PEZZO_ENVIRONMENT='Production'

PEZZO_PROJECT_ID_1='cm9kzcs94006bqk0h7adfc15u'

PEZZO_PROJECT_ID_2='cm9wimw5f006hqk0hz274icps'
 
PEZZO_PROJECT_ID_3='cmb4n1e9b006xqk0ht7n8ts3q'